### ISSUE TITLE
README

### ISSUE THREAD

**Issue by Lecrapouille** [Pandas-Team/Automatic-Parking#2]
Some typo in README.

1/ kinematic. 

Currently, written:
```
The kinematic model of the car is:
x = vcos(ϕ)
y = vsin(ϕ)
v = a
ϕ = vtan(δ)/L
```

1.1/ Missing derivative symbol `'`. Should be:
```
The kinematic model of the car is:
x' = v . cos(ϕ)
y' = v . sin(ϕ)
v' = a
ϕ' = v . tan(δ)/L
```

1.2/ Missing: `a: acceleration, δ: steering angle, ϕ: yaw angle, L: wheelbase, x: x-position, y: y-position, v: velocity`
1.3/ v was stuck to cos, sin, tan.

2/ The state vector.

The symbol φ should be ϕ

3/ The input vector

There is a typo `a: accellation, δ: steering angle` => acceleration :)

**Comment by amirhosseinh77** [comment]
Hi there,
Thank you very much for your attention and the feedback.
The typos mentioned have been corrected, and let us know if there is anything else that needs to be corrected.
Also, if you have any ideas to improve the code, we will be happy to know.

**Comment by Lecrapouille** [comment]
Hi, it's fine now ! I'm currently working on this kind of problematic, my maths is poor but in many papers, including your readme, they write like `ϕ' = v . tan(δ)/L` but I cannot understand why tan() since it looked like to me this should be ϕ' = v . sin(δ)/L. Specially when tan(pi/2) will return infinity (ok this will mean wheels are turned at 90° but, here we meant steering angle).

**Comment by amirhosseinh77** [comment]
This website provides some good info: http://planning.cs.uiuc.edu/node658.html
I drew this image and It's not that good, but I think it has all the information.
![eq](https://user-images.githubusercontent.com/56114938/128091124-11ac2227-32d6-4536-bc2e-a7ab783f928b.jpg)

**Comment by Lecrapouille** [comment]
ok, I forget that was obviously the same angle than the turning radius :)
We can close the ticket.
