### ISSUE TITLE
Question about vehicle length

### ISSUE THREAD

**Issue by kosuke55** [Pandas-Team/Automatic-Parking#3]
Thank you for your work. I have question about vehicle length.
`length=4` in https://github.com/Pandas-Team/Automatic-Parking/blob/master/CAR%20kinematic%20model/main_autopark.py#L53.
But is it better to be `length=5` because wheelbase is `50` in `1000 coordinates` (https://github.com/Pandas-Team/Automatic-Parking/blob/master/CAR%20kinematic%20model/environment.py#L12) and `5` in `100 coordinates`

**Comment by amirhosseinh77** [comment]
Hi there, thanks for your attention.
I think you are right and the only reason that ```length=4``` is selected is that the length of most cars is about 4 meters.
But it is more precise to choose 5 as length.
Thanks for pointing that out.

**Comment by kosuke55** [comment]
Thanks for the quick answer. I understand.

**Comment by lkz98** [comment]
> 

may i have your email address, please

**Comment by amirhosseinh77** [comment]
Of course
amirhossein261077@live.com
