### ISSUE TITLE
Questions about environment

### ISSUE THREAD

**Issue by renyumeng1** [Pandas-Team/Automatic-Parking#4]
If I want to create a new parking lot map and create new obstacles, what are the coordinates of obstacles and walls based on in the example?

**Comment by amirhosseinh77** [comment]
Hi there,
As you can see in (line 33)[https://github.com/Pandas-Team/Automatic-Parking/blob/b761ebf6810c0678034da95ae631f7d84373006d/CAR%20kinematic%20model/main_autopark.py#L33] of the main code, there are some obstacles generated by parking 1.
You can delete that line and get rid of the parking structure.
If you want to make your parking, use parking 1 class as a template, and to clarify the coordinates, remember that the background is based on a 100*100 grid.
There are also some commented lines 35-48 that can be used to add more obstacles, even squares.
