### ISSUE TITLE
problem about car control

### ISSUE THREAD

**Issue by Phymin** [Pandas-Team/Automatic-Parking#5]
Hi,

Please see the attached video, I don't change any thing, but the control looks very wired, could someone tell me what the problem is? Thanks.

https://user-images.githubusercontent.com/9857420/169484973-ff404723-defd-4bae-a209-db1be99bea64.mp4

**Comment by amirhosseinh77** [comment]
Hi, I assume that you used the code with dynamics.
It still doesn't work and is under development.
Use the code in the kinematic folder, and it must be ok.
